Malibu.xcodeproj/project.pbxproj
MalibuTests/Helpers/Mocks.swift
MalibuTests/Helpers/TestRequest.swift
MalibuTests/Specs/MalibuSpec.swift
MalibuTests/Specs/Mocks/MockDataTaskSpec.swift
MalibuTests/Specs/Mocks/MockSpec.swift
MalibuTests/Specs/NetworkingSpec.swift
MalibuTests/Specs/Request/MethodSpec.swift
MalibuTests/Specs/Tasks/NetworkTaskRunningSpec.swift
MalibuTests/Specs/Tasks/SessionDataTaskSpec.swift
Sources/Error.swift
Sources/Malibu.swift
Sources/Mocks/Mock.swift
Sources/Mocks/MockDataTask.swift
Sources/Mocks/MockRequest.swift
Sources/Networking.swift
Sources/Request/Method.swift
Sources/Request/URLStringConvertible.swift
Sources/Tasks/NetworkTaskRunning.swift
Sources/Tasks/SessionDataTask.swift

@zenangst @RamonGilabert @onmyway133 
1) Register network with name + default networking instance:
```swift
let networking = Networking(baseURLString: "http://hyper.no/api")
Malibu.register("hyper", networking: networking)
networkingNamed("hyper") // => registered instance
networkingNamed("random") // => backfootSurfer default networking instance 
```
2) Request mocks. You can easily mock your request for testing.
```swift
struct TestRequest: Requestable {
var message = Message(resource: "http://hyper.no")
}
let request = TestRequest()
let response = NSHTTPURLResponse(URL: NSURL(string: "http://hyper.no")!,
statusCode: 200, HTTPVersion: "HTTP/2.0", headerFields: nil)!
let data = "test".dataUsingEncoding(NSUTF32StringEncoding)
let mock = Mock(request: request, response: response, data: …
```

Feature: mocked requests

---

.travis.yml
Sources/Malibu.swift
Sources/Networking.swift

This PR adds a new mode when mocking requests, before we had `.Regular` and `.Fake`.
The new mode `.Partial` looks for mocked requests, if there are any, use them, if they don't exist it tries to do an actual request.
This can be helpful when developing towards an API that is still being built alongside the client.

Feature Partial mocking

---

MalibuTests/Specs/NetworkingSpec.swift
Sources/Networking.swift

Closure to modify the each request:
```swift
networking.beforeEach = { request in
var request = request
request.message.parameters["test"] = true
return request
}
```

Feature: pre process request

---

Sources/Networking.swift

Sometimes additional headers are dynamic values, so you can't just set it once.

Implement additional headers as a closure

---

Malibu.xcodeproj/project.pbxproj
MalibuTests/Helpers/Mocks.swift
MalibuTests/Helpers/NetworkPromiseSpec.swift
MalibuTests/Specs/Mocks/MockDataTaskSpec.swift
MalibuTests/Specs/Response/WaveSerializationSpec.swift
MalibuTests/Specs/Response/WaveSpec.swift
MalibuTests/Specs/Response/WaveValidationSpec.swift
MalibuTests/Specs/Tasks/SessionDataTaskSpec.swift
MalibuTests/Specs/Tasks/TaskRunningSpec.swift
MalibuTests/Specs/Validation/ContentTypeValidatorSpec.swift
MalibuTests/Specs/Validation/StatusCodeVadatorSpec.swift
Sources/Malibu.swift
Sources/Mocks/MockDataTask.swift
Sources/Networking.swift
Sources/Request/Ride.swift
Sources/Response/Wave.swift
Sources/Response/WaveSerialization.swift
Sources/Response/WaveValidation.swift
Sources/Tasks/SessionDataTask.swift
Sources/Tasks/TaskRunning.swift
Sources/Validation/ContentTypeValidator.swift
Sources/Validation/StatusCodeValidator.swift
Sources/Validation/Validating.swift

All the request functions return `Ride` object which you can use in the following way:
1) As promise:
```swift
let ride = Malibu.GET(Request(parameters: parameters))
ride.validate()
.toJSONDictionary()
.done({ data in
print(data)
})
.fail({ error in
print(error)
})
```
2) As a task:
```swift
ride.cancel()
```
Also boring `NetworkResult` is renamed to `Wave`, so now we have `Promise<Wave>`.

Feature: ride and wave

---

Malibu.xcodeproj/project.pbxproj
Sources/Helpers/Utils.swift
Sources/Logging.swift
Sources/Malibu.swift
Sources/Networking.swift
Sources/Tasks/SessionDataTask.swift

Now you can disable and enable logging and provide your own logging method:
```swift
// MARK: - Errors
struct CustomErrorLogger: ErrorLogging {
func logError(error: ErrorType) {
NSLog("\(error)")
}
}
// MARK: - Info
struct CustomInfoLogger: InfoLogging {
func logRequest(request: NSURLRequest) {
guard let URLString = request.URL?.absoluteString else {
return
}
NSLog("\(URLString)")
}
}
Malibu.logger.infoLogger = CustomInfoLogger()
Malibu.logger.errorLogger = CustomInfoLogger()
Malibu.logger.level = .Debug
```
If you just set a logging level so something other than `.Disabled` and don't specify custom loggers, then defaults loggers will be used.

Feature: logging

---

Cartfile.resolved
MalibuTests/Specs/Request/HeaderSpec.swift
Sources/Helpers/Utils.swift
Sources/Request/Header.swift

Since `operatingSystemVersionString` is localized, it is not good to be used in user agent
```
Version 9.1 (Build 13B143)
```
> The operating system version string is human readable, localized, and is appropriate for displaying to the user. This string is not appropriate for parsing
This fixes that by constructing os info, without build number due to lack of official API, so it will be like `iOS 9.1.0`

Update os info

---

Malibu.xcodeproj/project.pbxproj
MalibuTests/Specs/Encoding/MultipartFormEncoderSpec.swift
MalibuTests/Specs/Helpers/MultipartBuilderSpec.swift
Sources/Encoding/MultipartFormEncoder.swift
Sources/Helpers/MultipartBuilder.swift
Sources/Malibu.swift
Sources/Request/ContentType.swift

Move `buildMultipartString` method to a new `MultipartBuilder` struct in order to use it separately.

Refactor: multipart form encoding

---

Sources/Networking.swift

"Middleware" is the function which works with the first promise in the chain, before the actual request. It could be used to prepare networking, do some kind of pre-processing task, cancel request under particular conditions, etc.
For example, in the combination with https://github.com/hyperoslo/OhMyAuth
```swift
// In your configuration
// Remember to `resolve` or `reject` the promise
networking.middleware = { promise in
AuthContainer.serviceNamed("service")?.accessToken { accessToken, error in
if let error == error {
promise.reject(error)
return
}
guard let accessToken = accessToken else {
promise.reject(CustomError())
return
}
self.networking.authenticate(bearerToken: accessToken)
promise.resolve()
}
}
// Send your request like you usually do
networking.GET(request)
.validate() …
```

Middleware promise

---

Malibu.xcodeproj/project.pbxproj
MalibuTests/Specs/ErrorSpec.swift
MalibuTests/Specs/MalibuSpec.swift
MalibuTests/Specs/Request/ContentTypeSpec.swift
MalibuTests/Specs/Request/RequestCapsuleSpec.swift
MalibuTests/Specs/Request/RequestStorageSpec.swift
MalibuTests/Specs/Request/RequestableSpec.swift
README.md
Sources/Error.swift
Sources/Malibu.swift
Sources/Networking.swift
Sources/Request/ContentType.swift
Sources/Request/ETagPolicy.swift
Sources/Request/RequestCapsule.swift
Sources/Request/RequestPolicies.swift
Sources/Request/RequestStorage.swift
Sources/Request/Requestable.swift

@zenangst @RamonGilabert @onmyway133 
💥 Request storage is migrated from https://github.com/hyperoslo/Offline. But it's not just a copy.  It adopted to Malibu types and works with promises.
- Want to store request to `NSUserDefaults` when there is no network connection to replay it later?
```swift
struct GETRequest: GETRequestable {
var message = Message(resource: "http://hyper.no")
var storePolicy: StorePolicy = .Offline
init(parameters: [String: AnyObject] = [:], headers: [String: String] = [:]) {
message.parameters = parameters
message.headers = headers
}
}
```
- Want to replay cached requests?
```swift
networking.replay().done({ result
print(result)
})
```
Request storage is networking-specific, and while it replays cached request it will be set to `Sync` mode. Cached request will go …

Feature: offline cache of requests

---

Sources/Networking.swift

So that we can pass the certain `Requestable` object, ideal for someone migrating to Malibu 😄

Make execute method public

---

Sources/Helpers/QueryBuilder.swift
Sources/Networking.swift

According to `index` function
> An index offset by n from the index i, unless that index would be beyond limit in the direction of movement. In that case, the method returns nil.
This won't work for string with count smaller than batch size because of the guard
So this fixes by fallbacks to `string.endIndex`. Hope the very small potion of iOS 8.1 and 8.2 users will like this 😄

Fix query builder

---

MalibuTests/Specs/Request/HeaderSpec.swift
Sources/Request/Header.swift

- We have `accept language`, so I think that should be in the default headers, too 😄 
- Make `Header` public, as when we have our own login networking, we can reuse these default headers

Make Header public

---

Sources/Request/Header.swift

Before
```
MyApp/32 (com.example.MyApp; build:32; iOS 10.1.1) Malibu/2.0.1
```
After
```
MyApp/0.0.26 (com.example.MyApp; build:32; iOS 10.1.1) Malibu/2.0.1
```

Fix version to use version string

---

MalibuTests/Specs/Request/RequestableSpec.swift
Sources/Request/Requestable.swift

This handles the url for the user, so there is less room for errors with slashes. User can specify
- baseURL: `http://hyper.no/` or `http://hyper.no`
- path: `about` or `/about`

Construct request URL

---

Malibu.xcodeproj/project.pbxproj
MalibuTests/Helpers/Mocks.swift
MalibuTests/Specs/NetworkingSpec.swift
Playground-iOS.playground/Contents.swift
README.md
Sources/Networking.swift
Sources/Request/Request.swift
Sources/Request/RequestConvertible.swift

⚠️ **Breaking change** ⚠️ 
1) `Endpoint` protocol was renamed to `RequestConvertible` in order to make it more descriptive.
2) Mock property is removed from `Request`. When the mock is created in one single place it is not really flexible for unit testing if you want to inject JSON dictionary or custom file dynamically. That's why `MockProvider` was introduced in order to improve mock behaviour:
In order to start mocking you have to do the following:
**Create a mock provider**
```swift
// Delay is optional, 0.0 by default.
let mockProvider = MockProvider(delay: 1.0) { endpoint in
switch endpoint {
case .fetchBoards:
// With response data from a file:
return Mock(fileName: "boards.json")
case .showBoard(let id):
// With response from JSON dictionary:
return Mock(json: ["id": 1, "title": …
```

Feature: ResponseConvertible and mock provider

---

MalibuTests/Helpers/Mocks.swift
MalibuTests/Specs/Response/MockSpec.swift
Playground-iOS.playground/Contents.swift
README.md
Sources/Networking.swift
Sources/Request/RequestConvertible.swift

This PR aims to fix https://github.com/hyperoslo/Malibu/issues/61 by making `baseUrl` in `RequestConvertible` optional.
```swift
static var baseUrl: URLStringConvertible? { get }
```
`let backfootSurfer = Networking<AnyEndpoint>()` didn't work before because its `baseUrl` was an empty string, which is wrong and breaks the logic of building the final request URL. And actually I think it makes sense to have optional `baseUrl` in `RequestConvertible` implementations, for cases when you want to group requests without any shared host.

Improve: request convertable base url

---

.travis.yml
MalibuTests/Specs/NetworkingSpec.swift
Sources/Networking.swift

The way we handled authentication challenges doesn't handle all the cases, basically it worked only when there is a base URL. Now we do multiple validations and call `completionHandler` in the end of the delegate function.

Fix: authentication challenge

---

Sources/Networking.swift

It could be useful to suspend and resume operation queue, for example during refresh token tasks.

Suspend and resume networking

---

MalibuTests/Specs/Response/ResponseHandlerSpec.swift
Sources/Networking.swift
Sources/Operation/ConcurrentOperation.swift
Sources/Operation/DataOperation.swift
Sources/Operation/MockOperation.swift
Sources/Response/ResponseHandler.swift

To have all the headers up to date it makes sense to create `URLRequest` in operation `execute` method.

Delay URL request creation

---

.swiftlint.yml
Cartfile.resolved
Sources/Request/Ride.swift

Requires adding `open override` to `Ride.cancel()` and adding a SwiftLint rule exception to not cause a build error due to uppercased enum cases. This is done to not have to break the public API.
Note that this PR is targeting a `4.1.1` update release, not `master`.

Update dependencies to get new version of When

---

MalibuTests/Specs/Request/RequestSpec.swift
Sources/Request/Request.swift

This bug was introduced in https://github.com/hyperoslo/Malibu/pull/57. Apparently `appendingPathComponent` applies URL percent encoding, but we don't want to do that when a request is built using query parameters:
```swift
Request.get("search?q=text")
```

Fix: construct request URL with query parameters

---

Sources/Request/Request.swift

If the URL you are requesting is already a valid URL, Malibu shouldn't convert it to String and attempt to create a new URL object.

Tiny improvement to the request builder

---

Sources/Response/ResponseValidation.swift

Right now, the default `.validate()` fails when receiving a HTTP 204 NO CONTENT response trough Express, as [Express strips away those fields when not needed](https://github.com/expressjs/express/blob/9375a9afa9d7baa814b454c7a6818a7471aaef00/lib/response.js#L192-L198).
If the maintainers agree, I'd like to remove 204 from the standard `.validate()` method in ResponseValidation.swift.
Edit: 
A more detailed explanation of why it doesn't work: If you set `application/json` as `Accept` and receive a 204, Express strips the `Content-Type` field making NSURLRequest do its best to guess the `Content-Type` itself, and as Express does `chunk = ''` on a 204, it assumes its `text/plain`. That obviously fails content type validation.

Remove validation of 204 responses in .validate()

---

Malibu.xcodeproj/project.pbxproj

Related to #96.
Submitting a version built this way got rejected from the AppStore, so we remove the 'included' dependency from Malibu, to the main project, circumventing the issue

Not including When in built framework

---

Malibu.xcodeproj/project.pbxproj
MalibuTests/Specs/Response/ResponseDecodingSpec.swift
README.md
Sources/NetworkError.swift
Sources/Response/ResponseDecoding.swift

Add response decoding using Decodable
